export const TEAMS = [
  { name: "Estados Unidos", code: "USA", group: "A" },
  { name: "Marruecos", code: "MAR", group: "A" },
  { name: "Paises Bajos", code: "NED", group: "A" },
  { name: "Canada", code: "CAN", group: "A" },
  { name: "Argentina", code: "ARG", group: "B" },
  { name: "Peru", code: "PER", group: "B" },
  { name: "Ucrania", code: "UKR", group: "B" },
  { name: "Australia", code: "AUS", group: "B" },
  { name: "Mexico", code: "MEX", group: "C" },
  { name: "Ecuador", code: "ECU", group: "C" },
  { name: "Japon", code: "JPN", group: "C" },
  { name: "Gales", code: "WAL", group: "C" },
  { name: "Brasil", code: "BRA", group: "D" },
  { name: "Colombia", code: "COL", group: "D" },
  { name: "Corea del Sur", code: "KOR", group: "D" },
  { name: "Paraguay", code: "PAR", group: "D" },
  { name: "Inglaterra", code: "ENG", group: "E" },
  { name: "Senegal", code: "SEN", group: "E" },
  { name: "Serbia", code: "SRB", group: "E" },
  { name: "Chile", code: "CHI", group: "E" },
  { name: "Alemania", code: "GER", group: "F" },
  { name: "Uruguay", code: "URU", group: "F" },
  { name: "Turquia", code: "TUR", group: "F" },
  { name: "Camerun", code: "CMR", group: "F" },
  { name: "Francia", code: "FRA", group: "G" },
  { name: "Iran", code: "IRN", group: "G" },
  { name: "Costa Rica", code: "CRC", group: "G" },
  { name: "Nigeria", code: "NGA", group: "G" },
  { name: "Espana", code: "ESP", group: "H" },
  { name: "Arabia Saudita", code: "KSA", group: "H" },
  { name: "Ghana", code: "GHA", group: "H" },
  { name: "Nueva Zelanda", code: "NZL", group: "H" },
  { name: "Portugal", code: "POR", group: "I" },
  { name: "Dinamarca", code: "DEN", group: "I" },
  { name: "Panama", code: "PAN", group: "I" },
  { name: "Eslovenia", code: "SVN", group: "I" },
  { name: "Italia", code: "ITA", group: "J" },
  { name: "Belgica", code: "BEL", group: "J" },
  { name: "Suiza", code: "SUI", group: "J" },
  { name: "Bolivia", code: "BOL", group: "J" },
  { name: "Croacia", code: "CRO", group: "K" },
  { name: "Venezuela", code: "VEN", group: "K" },
  { name: "Egipto", code: "EGY", group: "K" },
  { name: "Bahrain", code: "BHR", group: "K" },
  { name: "Polonia", code: "POL", group: "L" },
  { name: "Costa de Marfil", code: "CIV", group: "L" },
  { name: "Honduras", code: "HON", group: "L" },
  { name: "Trinidad y Tobago", code: "TRI", group: "L" },
] as const;

export function getFlagUrl(code: string): string {
  const codeMap: Record<string, string> = {
    USA: "us", ARG: "ar", BRA: "br", MEX: "mx", CAN: "ca",
    MAR: "ma", NED: "nl", PER: "pe", UKR: "ua", AUS: "au",
    ECU: "ec", JPN: "jp", COL: "co", KOR: "kr", PAR: "py",
    ENG: "gb-eng", SEN: "sn", SRB: "rs", CHI: "cl", GER: "de",
    URU: "uy", TUR: "tr", CMR: "cm", FRA: "fr", IRN: "ir",
    CRC: "cr", NGA: "ng", ESP: "es", KSA: "sa", GHA: "gh",
    NZL: "nz", POR: "pt", DEN: "dk", PAN: "pa", SVN: "si",
    ITA: "it", BEL: "be", SUI: "ch", BOL: "bo", CRO: "hr",
    VEN: "ve", EGY: "eg", BHR: "bh", POL: "pl", CIV: "ci",
    WAL: "gb-wls", TRI: "tt", HON: "hn",
  };
  const cc = codeMap[code] || code.toLowerCase();
  return `https://flagcdn.com/w80/${cc}.png`;
}
